name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: setVersion
        run: |
          v=`git describe --tags --always`
          version=${v//-/.}
          echo "version=${v//-/.}" >> $GITHUB_ENV 

      - name: i commang
        run: |
          git describe --tags --always --abbrev=0
          git describe --tags --always
          echo ${{ env.version }}
      
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ env.version }} 
          message: "Latest release"
